export const projects = [ 
  { id: 1, title: 'По проекту', checked: false },
  { id: 2, title: 'Объекты', checked: false },
  { id: 3, title: 'РД', checked: false },
  { id: 4, title: 'МТО', checked: false },
  { id: 5, title: 'СМР', checked: true },
  { id: 6, title: 'График', checked: false },
  { id: 7, title: 'МиМ', checked: false },
  { id: 8, title: 'Рабочие', checked: false },
  { id: 9, title: 'Капвложения', checked: false },
  { id: 10, title: 'Бюджет', checked: false },
  { id: 11, title: 'Финансирование', checked: false },
  { id: 12, title: 'Панорамы', checked: false },
  { id: 13, title: 'Камеры', checked: false },
  { id: 14, title: 'Поручения', checked: false },
  { id: 15, title: 'Контрагенты', checked: false },
]; 
